"""Initial migration.

Revision ID: a9d0921039ee
Revises: 
Create Date: 2022-03-30 11:58:19.002352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d0921039ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sa.String(length=20), nullable=True),
    sa.Column('conta_origem', sa.String(), nullable=True),
    sa.Column('cpf_origem', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('conta_destino', sa.String(), nullable=True),
    sa.Column('cpf_destino', sa.String(), nullable=True),
    sa.Column('id_transacao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transacao')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('transacao')
    # ### end Alembic commands ###
